[package]
name = "Peek"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2.4.0"
zip = "0.6"
lettre = { version = "0.11", features = ["smtp-transport", "builder", "tokio1-native-tls"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15" # for environment variables